sections:
  interface:
    type: operational
    priority: 10
    processor: InterfaceProcessor
  
  ospf:
    type: operational
    priority: 20
    processor: OSPFProcessor
  
  config:
    type: configuration
    priority: 0
    processor: ConfigProcessor
  
  arp:
    type: relationship
    priority: 30
    processor: ARPProcessor